import Head from "next/head";

import overlay from "@/images/overlay.png";

import emp from "@/images/BG_EMP.jpg";
// import test2 from "@/images/test2.jpg";
// import test3 from "@/images/test3.jpg";

import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, EffectFade } from "swiper/modules";

import "swiper/css";
import "swiper/css/effect-fade";

import Image from "next/image";
import { useQuery } from "@tanstack/react-query";

type ImageType = {
  created: EpochTimeStamp;
  filename: string;
  url: string;
};

export default function Home() {
  // Queries
  const { data } = useQuery<{ assets: ImageType[] }>({
    queryKey: ["slides"],
    queryFn: async () => {
      const response = await fetch("https://assets.marcustut.me/assets");
      if (!response.ok) {
        throw new Error("Network response was not ok");
      }

      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      const res = await response.json();

      console.log("res", res);
      // eslint-disable-next-line @typescript-eslint/no-unsafe-return
      return res;
    },
    refetchInterval: 5000,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data?.assets && data?.assets.length > 0 ? (
        <main className="relative h-[1000px] w-[4000px]">
          <Image
            src={overlay}
            alt="Overlay"
            className="relative z-10 h-[1000px] w-[4000px]"
          />
          <div className="absolute left-[50%] top-[5%] h-[855px] w-[1520px]">
            <Swiper
              autoplay={{
                delay: 5000,
                disableOnInteraction: false,
              }}
              modules={[EffectFade, Autoplay]}
              effect="fade"
            >
              {data?.assets?.map((d, i) => (
                <SwiperSlide key={i}>
                  <Image
                    src={d.url}
                    alt={String(i)}
                    width={5472}
                    height={3072}
                    className="h-full w-full object-cover object-center"
                  />
                </SwiperSlide>
              ))}
            </Swiper>
          </div>
        </main>
      ) : (
        <Image src={emp} alt="EmptyScreen" />
      )}
    </>
  );
}
